# This Makefile is designed specifically for building programs written 
# in Inform.  Feel free to adopt and adapt it for your own purposes.
#

VERSION = r2
BINNAME = uninvited
EXTENSION = .z5
BLORB_EXTENSION = .zblorb

INFORM = inform
#BLORB = pblorb.pl
BLORB = cBlorb

NODEBUG = -~D~S
DEBUG = -D

GLULX = -G
SWITCHES = -iecd2 '$$MAX_OBJECTS=768'

DISTNAME = $(BINNAME)-$(VERSION)
distdir = $(DISTNAME)

#exclude = --exclude=misc --exclude=junk

blurbfile = src/blurb.inf

$(BINNAME): blorb
	cd src ; $(INFORM) $(SWITCHES) $(DEBUG) $(BINNAME).inf ../$(BINNAME)$(EXTENSION)

nodebug: blorb
	cd src ; $(INFORM) $(SWITCHES) $(NODEBUG) $(BINNAME).inf ../$(BINNAME)$(EXTENSION)

blorb:
	touch $(BINNAME)$(EXTENSION) $(BINNAME)$(BLORB_EXTENSION)
	$(BLORB) sound/$(BINNAME).blurb $(BINNAME)$(BLORB_EXTENSION) > src/blurb.inf

abbrev:
	rm -f src/abbreviations.inf
	@echo "! This file is automatically generated from the Makefile" >> src/abbreviations.inf
	@echo "! Do not edit." >> src/abbreviations.inf
	@echo >> src/abbreviations.inf
	cd src ; $(INFORM) $(SWITCHES) -u $(BINNAME).inf | grep "^Abbreviate" >> abbreviations.inf

gametext:
	cd src ; $(INFORM) $(SWITCHES) -r $(BINNAME).inf

glulx:
	cd src ; $(INFORM) $(GLULX) $(SWITCHES) $(BINNAME).inf ../$(BINNAME).ulx
	
dist: distclean
	mkdir $(distdir)
	@for file in `ls`; do \
		if test $$file != $(distdir); then \
			cp -rp $$file $(distdir)/$$file; \
		fi; \
	done
	tar chof $(distdir).tar $(distdir) $(exclude)
	gzip -f --best $(distdir).tar
	rm -rf $(distdir)
	@echo
	@echo "$(distdir).tar.gz created"
	@echo 

clean:
	rm -f *core src/*.core src/gametext.txt
	rm -f *.sav
	rm -f $(BINNAME)$(EXTENSION)
	rm -f $(BINNAME)$(BLORB_EXTENSION)
	rm -f $(BINNAME).zip
#	rm -f *.ulx

distclean: clean
	-rm -f src/blurb.inf
	-rm -rf $(distdir)
	-rm -f $(distdir).tar $(distdir).tar.gz


help:
	@echo "Makefile for Inform compilation"
	@echo "Targets:"
	@echo "  $(BINNAME)	Build the game."
	@echo "  nodebug	Build the game without debugging code."
	@echo "  abbrev	Build abbreviation list."
	@echo "  blorb		Build Blorb file."
	@echo "  gametext	Output all game text."
	@echo "  dist		Create distribution tarball."
	@echo "  clean		Get rid of temporary files."
	@echo "  distclean	Get rid of anything not in the tarball."	
	@echo "  help		This help message."
	@echo "Default target is \"$(BINNAME)\""
